### ISSUE TITLE
No notifications on Win10 Creators Update (v2 beta 1)

### ISSUE THREAD

**Issue by Joerg123** [wokhansoft/WFN#1] opened 2017-05-25 22:58 UTC
Hi Daniel,

I'm using WFN for years now and really like it. But now, i have an issue with it again:

- windows task scheduler does not start WFN
- it says, task was never running
- I thinkt this problem starts after updating to Creators Update
- I have  a few more issues with other tasks which won't run correctly after this update, i think MS has worked a lot on task scheduler.

I use the update-check from vlc-player for triggering WFN. There is no rule for it, so it will be blocked. An Entry in the event log will be created, like it should:

----------------------------------------------------------------------------
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>5157</EventID> 
  <Version>1</Version> 
  <Level>0</Level> 
  <Task>12810</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2017-05-25T22:25:07.542709600Z" /> 
  <EventRecordID>28073</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="32" /> 
  <Channel>Security</Channel> 
  <Computer>JB-AW</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="ProcessID">5692</Data> 
  <Data Name="Application">\device\harddiskvolume4\program files\vlc\vlc.exe</Data> 
  <Data Name="Direction">%%14593</Data> 
  <Data Name="SourceAddress">192.168.2.104</Data> 
  <Data Name="SourcePort">1753</Data> 
  <Data Name="DestAddress">88.191.250.2</Data> 
  <Data Name="DestPort">80</Data> 
  <Data Name="Protocol">6</Data> 
  <Data Name="FilterRTID">365769</Data> 
  <Data Name="LayerName">%%14611</Data> 
  <Data Name="LayerRTID">48</Data> 
  <Data Name="RemoteUserID">S-1-0-0</Data> 
  <Data Name="RemoteMachineID">S-1-0-0</Data> 
  </EventData>
  </Event>
------------------------------------------------------------------------------

In my opinion, it should run the task, but it doesn't. The only thing, i noticed, is, that sometimes the LayerRTID is 50 instead of 48, but i can find both entries, so either way it should work?!

referring to https://wfn.codeplex.com/workitem/5245
After reading this, i put WFN to C:\, but no change.
Problem seems not to be WFN but the trigger of the task
Same issue with WFN v2 alpha 12

Do you see any reason for this behaviour?

Greetings
Jörg

**Comment by Joerg123** [comment] 2017-05-25 23:04
Why is GitHub hiding the event log, and how can i make it visible?
Again as screenshot:
![event](https://cloud.githubusercontent.com/assets/28968138/26474022/02d74426-41af-11e7-8ba8-dd53957b2aca.PNG)
Greetings
Jörg

**Comment by AtlasHackert** [comment] 2017-05-30 16:51
I see no reason why it shouldn't work... Something indeed must have changed in the way Windows handles tasks, or how the Firewall works. I haven't updated to the Creators Update yet, so currently I can't test it, but I'll see if I can get my hands on a test computer with it.

**Comment by Joerg123** [comment] 2017-05-30 16:58
I don't know, it's strange. Sometimes it works, sometimes not. Yesterday it worked, today it doesn't.

I have an other problem as well:
I returned to v 2 alpha12 because v2b1 doesn't create rules at all, no matter if you press allow or block, no new rule will be created.

greetings
Jörg

**Comment by AtlasHackert** [comment] 2017-05-30 19:08
> I returned to v 2 alpha12 because v2b1 doesn't create rules at all, no matter if you press allow or block, no new rule will be created.

Yeah, there's a very nice bug I introduced in Beta 1; I already have it fixed. Note to self: Probably should do a Beta 2 release soon...

**Comment by AtlasHackert** [comment] 2017-06-02 15:23
@Joerg123: I've just release 2.0 Beta 2; can you please try that version?

**Comment by Joerg123** [comment] 2017-06-02 18:15
Yes, I will try it.

I found a small bug:
If i jump from anything to map and than directly to connections, and the connections on the map weren't loaded yet, i get an error, that WFN can't access to ipDatabase.gz because it is used by an other process.

Greetings Jörg

**Comment by afatac** [comment] 2017-06-14 06:53
My Windows 10 is not updated to Windows 10 Creators yet, but there is also no notification for 2.0 Beta 2. Here is the error message shown in Event Viewer. The notification works in 2.0 Alpha which is what I am using now.

[![image](https://user-images.githubusercontent.com/26587885/27119063-e6975f82-5110-11e7-8d82-390cc9476a4c.png)
](url)

**Comment by AtlasHackert** [comment] 2017-06-14 15:10
@afatac: Do you have writing rights to the WFN folder (e.g. it's NOT in Program Files), or is the log file read-only?

**Comment by afatac** [comment] 2017-06-14 21:07
The folder is in Program Files and the log file is writeable
 
![image](https://user-images.githubusercontent.com/26587885/27154505-e109b48a-5187-11e7-8600-44f805e7b44c.png)

This is another error message in Event Viewer

![image](https://user-images.githubusercontent.com/26587885/27154603-38762906-5188-11e7-8229-ce494ddf95c6.png)

**Comment by AtlasHackert** [comment] 2017-06-15 05:04
The Program Files folder is writable for Administrators (and SYSTEM); this is how the Notifier gets launched. But then it has to drop to your normal user account to display, and then it can't write to the Program Files folder (unless you've changed its settings, in which case I strongly suggest you put that back, because you've just compromised a major security barrier of Windows).

WFN currently doesn't work properly when you install it in Program Files, because of this. Try running WFN from outside it.

**Comment by h3298** [comment] 2017-06-23 08:56
> I'm using WFN for years now and really like it. But now, i have an issue with it again:
> windows task scheduler does not start WFN

I can confirm this issue.  Its not just on Windows 10.  When I launch WFN from Task Scheduler using the manual control (right-click, RUN) I see it in Task Manager but no user interface appears on screen.  Status in Task Scheduler is "Queued".

**Comment by tgp1994** [comment] 2017-09-27 22:14
@AtlasHackert I was thinking about helping tackle this issue... Would it make sense to focus on creating an installer for WFN releases so it can be properly installed to the Program Files folder? It sounds like we'd have to change how some files are written since I think writing to anywhere in the Program Files folder during normal program operation is discouraged at least. Perhaps we can implement a "portable" mode so users can continue to run it as always?

**Comment by AtlasHackert** [comment] 2017-09-28 15:03
> Would it make sense to focus on creating an installer for WFN releases so it can be properly installed to the Program Files folder?

Yes. Preferably an .msi, so that WFN can be pushed onto machines in a domain. However, I have no experience with this, and it seems quite complicated; that's why I haven't tried it yet.

> It sounds like we'd have to change how some files are written since I think writing to anywhere in the Program Files folder during normal program operation is discouraged at least.

It's the log-file (it always is with WFN, isn't it? :D ). It should be written to one of the AppData folder, or perhaps it should go through Windows' log infrastructure so it ends up in Event Viewer. In the latter case we'd also no have to worry about taking up too much space, as Windows will handle that automatically.

But I haven't really looked into what it takes to set that up.

> Perhaps we can implement a "portable" mode so users can continue to run it as always?

That is also important; but where do we leave the logs then?

**Comment by tgp1994** [comment] 2017-09-28 15:12
I was thinking that in portable mode at least, the log would continue to
generate next to the executable. Ultimately I imagine we can make this a
user-selectable option, but by default it could go like this:

1. Pick Windows Event Reporting by default
2. Save the log file to a temp folder (fall back here if the event
reporting service isn't running for whatever reason)
3. Don't do any writing at all (unwritable file system?)

Should I make a separate issue to discuss logging specifically?

**Comment by AtlasHackert** [comment] 2017-09-28 15:14
Sounds pretty good.

> Should I make a separate issue to discuss logging specifically?

Yes, please.

**Comment by wokhan** [comment] 2020-03-08 20:05
Logging: see #20 
Installer: see #21, #32, #53 (directly or indirectly related). An installer will be added for the next release. 
Locked IPDatabase: the gzip file is no longer used so it should not happen anymore. Will double check anyway. 
Automated task issue: this won't be the default behavior from now on, so it's not applicable anymore. 

Closing the issue (with the aforementioned follow-ups).

**Closed by wokhan** 2020-03-08 20:05 UTC
Labels: bug
