### ISSUE TITLE
Mode where outgoing connections are allowed permanently on a binary basis

### ISSUE THREAD

**Issue by sztanpet** [wokhansoft/WFN#16] opened 2017-08-15 17:25 UTC
Right now, when I enable blocking and prompting for outgoing connections, I get a notification for every single connection something makes which makes it absolutely unusable (think torrent clients).
I am wondering if it is possible to only ask once for a binary and than allow all outgoing connections (which is what I would presume most people would want).
I notice that there are advanced options when allowing something, if that is where to do this, I am wondering how I can set the defaults so I dont have to micro-manage so much.
Thanks!

**Comment by AtlasHackert** [comment] 2017-08-16 06:17
Yes, you have to disable the "local port" and "target port" (and perhaps even the "protocol") options in the Advanced panel. Then WFN will create a rule for the entire executable.

Currently, there's no way to change the default behavior, but that's a good idea! I'll add it as a feature request.

**Comment by sztanpet** [comment] 2017-08-16 08:04
Also, if I have enabled the always run as admin option, it would be nice if it did not ask me every single time for consent after clicking allow

**Comment by AtlasHackert** [comment] 2017-09-08 20:58
Since the pop-up runs as the current user, it unfortunately has to ask for elevation every time you want to create a new firewall rule: it's part of Windows' security system.

**Comment by KyleKirkpatrick** [comment] 2018-03-16 00:13
Ahh, I get it now. 

I couldn't figure out if the toggles in the advanced panel were restricting the rule to those parameters, or allowing those parameters. 

In general, it would be handy to have some tool tips and documentation for the Advanced rule settings. 

I get it now though, thank you.

**Comment by wokhan** [comment] 2020-03-08 20:22
Duplicate of #29 (program trust option). 
Will add a way to simplify this.

**Closed by wokhan** 2020-03-08 20:22 UTC
Labels: enhancement
