### ISSUE TITLE
WFN becomes unstable when alerts are ignored (beta 3)

### ISSUE THREAD

**Issue by kekukui** [wokhansoft/WFN#39] opened 2018-03-11 10:02 UTC
**Event ID 1000**

Faulting application name: Notifier.exe, version: 2.0.0.0, time stamp: 0x5a9abcf8
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23915, time stamp: 0x59b94abb
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x8ef0
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll

**Event ID 1026**

Application: Notifier.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at Wokhan.WindowsFirewallNotifier.Notifier.Program.Main(System.String[])

**Crash on alert dialog**

PF has blocked outgoing TCP (6) [S] packet from [] to [] (https)

![wfn crash 1](https://user-images.githubusercontent.com/20834957/37252069-666124f0-24f1-11e8-9fdb-740eb53fe0cc.PNG)
![wfn crash 2](https://user-images.githubusercontent.com/20834957/37252072-6baacc0e-24f1-11e8-8359-a27b562c285a.PNG)
![wfn crash 3](https://user-images.githubusercontent.com/20834957/37252073-6f73b17a-24f1-11e8-975c-fccab2cbaba2.PNG)

**Comment by AtlasHackert** [comment] 2018-03-11 19:57
The exception is due to a corrupt library-file somewhere: https://msdn.microsoft.com/en-us/library/system.io.fileloadexception(v=vs.90).aspx

Do you have .NET framework 4.5.2 installed? Can you do a repair on it?

**Comment by h3298** [comment] 2018-03-12 05:36
In PowerShell,

`  (Get-ItemProperty "HKLM:Software\Microsoft\NET Framework Setup\NDP\v4\Full").Version`

returns **4.7.02558**
______

![wfn dot net version](https://user-images.githubusercontent.com/20834957/37267257-70b6bc5e-2595-11e8-9425-75c51169c145.PNG)

Should I repair 4.7, or install 4.5.2 ?

**Comment by AtlasHackert** [comment] 2018-07-16 10:30
Sorry for not getting back to you sooner. Either option will do fine: .NET 4.7 is backward compatible with 4.5.2.

**Comment by h3298** [comment] 2018-07-24 15:06
**Uninstalled & reinstalled .NET but the issue persists: sometimes the alerts come too fast for me to answer, and when several alerts stack up, the same fault occurs:**

==========

**Error: "This application could not be started"**

The app is not configured in a way that makes it possible to determine the appropriate version of the .NET Framework runtime. The corresponding shim code is SHIM_NOVERSION_FOUND.

You can't fix the configuration problem yourself. Contact the app vendor to resolve the issue. 

https://support.microsoft.com/en-us/help/2715633/shim-errors-for-the-net-framework-version-and-platform-support

**Comment by BADJAG** [comment] 2018-08-11 08:48
Here's something you can try: go to the Task Scheduler (taskschd.msc), open the Notifier task's properties, go to the SETTINGS tab, and change the last setting from "RUN A NEW INSTANCE IN PARALLEL" to "QUEUE A NEW INSTANCE". This prevents multiple alerts from crashing the system.

**Comment by wokhan** [comment] 2020-03-07 08:21
Closing since we won't be able to reproduce.

**Closed by wokhan** 2020-03-07 08:21 UTC
Labels: wontfix
