### ISSUE TITLE
Stopped working in Win10 x64 v1809 b17763.134

### ISSUE THREAD

**Issue by donselmo** [wokhansoft/WFN#50] opened 2018-11-20 18:59 UTC
It seems WFN can't create an entry in windows scheduler or enabling the firewall log. Manipulating the WF however is still working. But the log is always empty  - or WFN can't reach it - and I can't find it in the scheduler so basically it's not working anymore. WFN log is full of error.
The WF was bugged the last mayor udate it's blocked everything, but MS hotfixed it. It seems they change so many other things too.
There is a way to add manually to the windows scheduler and enable WF logging? I give it a try to test that way.
[Wokhan.WindowsFirewallNotifier.Common.log](https://github.com/wokhansoft/WFN/files/2601097/Wokhan.WindowsFirewallNotifier.Common.log)

**Comment by wokhan** [comment] 2020-03-07 07:29
Closing this issue since it hasn't been reproduced.
Note if any further investigation is required: the log file has two issues:
- Object reference not set to an instance of an object (Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra) in Pages.EventsLog.btnLocate_Click.
- Failed to compare two elements in the array (Nem sikerült összehasonlítani a tömb két elemét) in Pages.Rules.filterRules (trigger by Collection.Add, and the underlying sorter).

**Closed by wokhan** 2020-03-07 07:29 UTC
